// Category group definitions for section ordering
export const CATEGORY_GROUPS = [
    'Grocery & Kitchen',
    'Snacks & Drinks',
    'Home & Personal Care',
];

export const CATEGORIES = [
    // Grocery & Kitchen
    {
        id: '1',
        name: 'Fruits & Vegetables',
        image: 'https://cdn-icons-png.flaticon.com/512/2153/2153786.png',
        icon: 'fruit-grapes',
        color: '#E8F5E9',
        group: 'Grocery & Kitchen',
    },
    {
        id: '2',
        name: 'Dairy & Breakfast',
        image: 'https://cdn-icons-png.flaticon.com/512/3050/3050158.png',
        icon: 'cow',
        color: '#E3F2FD',
        group: 'Grocery & Kitchen',
    },
    {
        id: '8',
        name: 'Atta, Rice & Dal',
        image: 'https://cdn-icons-png.flaticon.com/512/3082/3082045.png',
        icon: 'grain',
        color: '#FFFDE7',
        group: 'Grocery & Kitchen',
    },
    {
        id: '9',
        name: 'Masala, Oil & More',
        image: 'https://cdn-icons-png.flaticon.com/512/2515/2515183.png',
        icon: 'fire',
        color: '#FFEBEE',
        group: 'Grocery & Kitchen',
    },
    {
        id: '7',
        name: 'Bakery & Biscuits',
        image: 'https://cdn-icons-png.flaticon.com/512/3081/3081967.png',
        icon: 'bread-slice',
        color: '#FBE9E7',
        group: 'Grocery & Kitchen',
    },
    {
        id: '5',
        name: 'Instant & Frozen Food',
        image: 'https://cdn-icons-png.flaticon.com/512/1046/1046786.png',
        icon: 'snowflake',
        color: '#F3E5F5',
        group: 'Grocery & Kitchen',
    },
    // Snacks & Drinks
    {
        id: '6',
        name: 'Tea, Coffee & More',
        image: 'https://cdn-icons-png.flaticon.com/512/924/924514.png',
        icon: 'coffee',
        color: '#EFEBE9',
        group: 'Snacks & Drinks',
    },
    {
        id: '4',
        name: 'Cold Drinks & Juices',
        image: 'https://cdn-icons-png.flaticon.com/512/3076/3076070.png',
        icon: 'bottle-soda',
        color: '#E1F5FE',
        group: 'Snacks & Drinks',
    },
    {
        id: '3',
        name: 'Munchies',
        image: 'https://cdn-icons-png.flaticon.com/512/2553/2553691.png',
        icon: 'cookie',
        color: '#FFF3E0',
        group: 'Snacks & Drinks',
    },
    // Home & Personal Care
    {
        id: '10',
        name: 'Cleaning Essentials',
        image: 'https://cdn-icons-png.flaticon.com/512/995/995016.png',
        icon: 'spray-bottle',
        color: '#E0F7FA',
        group: 'Home & Personal Care',
    },
    {
        id: '11',
        name: 'Personal Care',
        image: 'https://cdn-icons-png.flaticon.com/512/2553/2553642.png',
        icon: 'account-heart',
        color: '#FCE4EC',
        group: 'Home & Personal Care',
    },
    {
        id: '12',
        name: 'Baby Care',
        image: 'https://cdn-icons-png.flaticon.com/512/3081/3081840.png',
        icon: 'baby-carriage',
        color: '#FBE9E7',
        group: 'Home & Personal Care',
    },
];

export const PRODUCTS = [
    {
        id: '1',
        name: 'Amul Taaza Toned Milk',
        description: 'Fresh toned milk with 3% fat content. Perfect for daily consumption.',
        price: 27,
        originalPrice: 30,
        discount: 10,
        unit: '500ml',
        image: 'https://cdn-icons-png.flaticon.com/512/3050/3050158.png',
        categoryId: '2',
        inStock: true,
        rating: 4.5,
        reviews: 234,
    },
    {
        id: '2',
        name: 'Fresh Onion',
        description: 'Farm fresh onions. Essential for Indian cooking.',
        price: 35,
        originalPrice: 40,
        discount: 12,
        unit: '1kg',
        image: 'https://cdn-icons-png.flaticon.com/512/1652/1652077.png',
        categoryId: '1',
        inStock: true,
        rating: 4.2,
        reviews: 567,
    },
    {
        id: '3',
        name: 'Lays American Style Cream & Onion',
        description: 'Crispy potato chips with cream and onion flavor.',
        price: 20,
        originalPrice: 20,
        discount: 0,
        unit: '52g',
        image: 'https://cdn-icons-png.flaticon.com/512/2553/2553691.png',
        categoryId: '3',
        inStock: true,
        rating: 4.7,
        reviews: 890,
    },
    {
        id: '4',
        name: 'Coca Cola',
        description: 'Refreshing cola drink. Perfect for any occasion.',
        price: 40,
        originalPrice: 45,
        discount: 11,
        unit: '750ml',
        image: 'https://cdn-icons-png.flaticon.com/512/3076/3076070.png',
        categoryId: '4',
        inStock: true,
        rating: 4.8,
        reviews: 1234,
    },
    {
        id: '5',
        name: 'Maggi 2-Minute Noodles',
        description: 'Instant noodles with masala flavor. Ready in 2 minutes.',
        price: 14,
        originalPrice: 14,
        discount: 0,
        unit: '70g',
        image: 'https://cdn-icons-png.flaticon.com/512/1046/1046786.png',
        categoryId: '5',
        inStock: true,
        rating: 4.6,
        reviews: 2345,
    },
    {
        id: '6',
        name: 'Tata Tea Gold',
        description: 'Premium blend of the finest Assam tea leaves.',
        price: 180,
        originalPrice: 200,
        discount: 10,
        unit: '500g',
        image: 'https://cdn-icons-png.flaticon.com/512/924/924514.png',
        categoryId: '6',
        inStock: true,
        rating: 4.4,
        reviews: 678,
    },
    {
        id: '7',
        name: 'Britannia Marie Gold',
        description: 'Light and crispy Marie biscuits. Perfect with tea.',
        price: 30,
        originalPrice: 35,
        discount: 14,
        unit: '250g',
        image: 'https://cdn-icons-png.flaticon.com/512/3081/3081967.png',
        categoryId: '7',
        inStock: true,
        rating: 4.3,
        reviews: 456,
    },
    {
        id: '8',
        name: 'Aashirvaad Whole Wheat Atta',
        description: '100% whole wheat atta for soft rotis.',
        price: 255,
        originalPrice: 280,
        discount: 9,
        unit: '5kg',
        image: 'https://cdn-icons-png.flaticon.com/512/3082/3082045.png',
        categoryId: '8',
        inStock: true,
        rating: 4.7,
        reviews: 789,
    },
    {
        id: '9',
        name: 'Fortune Sunflower Oil',
        description: 'Light and healthy refined sunflower oil.',
        price: 165,
        originalPrice: 180,
        discount: 8,
        unit: '1L',
        image: 'https://cdn-icons-png.flaticon.com/512/5787/5787016.png',
        categoryId: '9',
        inStock: true,
        rating: 4.5,
        reviews: 567,
    },
    {
        id: '10',
        name: 'Surf Excel Easy Wash',
        description: 'Powerful stain removal detergent powder.',
        price: 120,
        originalPrice: 140,
        discount: 14,
        unit: '1kg',
        image: 'https://cdn-icons-png.flaticon.com/512/995/995016.png',
        categoryId: '10',
        inStock: true,
        rating: 4.6,
        reviews: 890,
    },
    {
        id: '11',
        name: 'Fresh Tomato',
        description: 'Farm fresh red tomatoes. Rich in vitamins.',
        price: 30,
        originalPrice: 35,
        discount: 14,
        unit: '500g',
        image: 'https://cdn-icons-png.flaticon.com/512/1202/1202125.png',
        categoryId: '1',
        inStock: true,
        rating: 4.1,
        reviews: 345,
    },
    {
        id: '12',
        name: 'Mother Dairy Curd',
        description: 'Fresh and creamy curd. Made from pure milk.',
        price: 35,
        originalPrice: 38,
        discount: 8,
        unit: '400g',
        image: 'https://cdn-icons-png.flaticon.com/512/2674/2674486.png',
        categoryId: '2',
        inStock: true,
        rating: 4.4,
        reviews: 567,
    },
];


export const BANNERS = [
    {
        id: '1',
        title: 'Fresh Vegetables',
        subtitle: 'Up to 30% Off',
        image: 'https://picsum.photos/seed/veggies/400/200',
        color: '#4CAF50',
    },
    {
        id: '2',
        title: 'Dairy Products',
        subtitle: 'Buy 2 Get 1 Free',
        image: 'https://picsum.photos/seed/dairyproducts/400/200',
        color: '#2196F3',
    },
    {
        id: '3',
        title: 'Snacks Festival',
        subtitle: 'Flat 20% Off',
        image: 'https://picsum.photos/seed/snacksfest/400/200',
        color: '#FF9800',
    },
];

